### ISSUE TITLE
check "reserve" input when no numfmt is available

### ISSUE THREAD

**Issue by cancerAlot** [ArchiveTeam/IA.BAK#12]
input will only be checked if numfmt is available:
[line in iabak-helper](https://github.com/ArchiveTeam/IA.BAK/blob/master/iabak-helper#L53)

possible solution will be that input is only supported in GB/TB-format if numfmt is not available

(it is also interesting which systems don't support numfmt (it was released in 2013...))

**Comment by joeyh** [comment]
Fixed in 68cacc3d7eab687e234f43d3876e6898ac31005c
