### ISSUE TITLE
iabak chokes on disk with space in volume label

### ISSUE THREAD

**Issue by DDR0** [ArchiveTeam/IA.BAK#26]
**Scrollback:**

david@office-tower-linux:/media/david/2.7TB EHD/IA.BAK$ ./iabak
Already up-to-date.
Welcome to iabak version 0.1
ALPHA TEST, use with caution

Looks like this is a new IA backup. I'm going to put it in
/media/david/2.7TB EHD/IA.BAK/shard6
This will use some disk space. :)
Press Enter to confirm, or ctrl-C to cancel.
Installing a recent version of git-annex ...
--2015-05-26 08:06:59--  https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-i386.tar.gz
Resolving downloads.kitenet.net (downloads.kitenet.net)... 66.228.36.95, 2600:3c03::f03c:91ff:fe73:b0d2
Connecting to downloads.kitenet.net (downloads.kitenet.net)|66.228.36.95|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43003580 (41M) [application/x-gzip]
Saving to: 'git-annex-standalone-i386.tar.gz'

-annex-standalone-i386.tar  90%[===================================>     ]  36.91M   230KB/s   eta 42s  
Broadcast message from root@office-tower-linux (Tue 2015-05-26 08:13:11 PDT):

Password entry required for 'Please enter passphrase for disk ST1000DX001-1CM162 (cryptswap1) on none!' (PID 32450).
Please enter password with the systemd-tty-ask-password-agent tool!

annex-standalone-i386.tar.  94%[=====================================>   ]  38.59M   150KB/s   eta 25s  
Broadcast message from root@office-tower-linux (Tue 2015-05-26 08:13:22 PDT):

Password entry required for 'Please enter passphrase for disk ST1000DX001-1CM162 (cryptswap1) on none!' (PID 891).
Please enter password with the systemd-tty-ask-password-agent tool!

git-annex-standalone-i386. 100%[========================================>]  41.01M   167KB/s   in 6m 56s 

2015-05-26 08:13:56 (101 KB/s) - 'git-annex-standalone-i386.tar.gz' saved [43003580/43003580]

Installed in /media/david/2.7TB EHD/IA.BAK/git-annex.linux

cat: /media/david/2.7TB: No such file or directory
cat: EHD/IA.BAK/git-annex.linux/libdirs: No such file or directory
cat: /media/david/2.7TB: No such file or directory
cat: EHD/IA.BAK/git-annex.linux/gconvdir: No such file or directory
Cleaning up...
david@office-tower-linux:/media/david/2.7TB EHD/IA.BAK$

**Comment by joeyh** [comment]
This was actually a bug in git-annex; I've fixed it there, and if you get the next autobuild (available in about an hour from now) it should work. iabak doesn't use the autobuilds by default, but you can force it to by editing IA.BAK/install-git-annex and setting NEED_PRERELEASE=1

I haven't checked if iabak otherwise works in this situation, although I think we've been pretty good about quoting shell variables.

**Comment by DDR0** [comment]
Seems to have worked now, thanks.
