### ISSUE TITLE
cronjob fails if trying to update git-annex on a full disk

### ISSUE THREAD

**Issue by jmtd** [ArchiveTeam/IA.BAK#36]
By design, IA.BAK has filled the disk I offered it. Great! However, the cron job seems to expect some disk space in order to update git-annex, which it is very keen to do:

```
...
Installing a recent version of git-annex ...
--2015-06-10 11:55:38--  https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-i386.tar.gz
Resolving downloads.kitenet.net (downloads.kitenet.net)... 66.228.36.95, 2600:3c03::f03c:91ff:fe73:b0d2
Connecting to downloads.kitenet.net (downloads.kitenet.net)|66.228.36.95|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44282115 (42M) [application/x-gzip]
Saving to: 'git-annex-standalone-i386.tar.gz'

git-annex-standalone-i386.t   0%[                                              ]  40.00K   191KB/s
git-annex-standalone-i386.t 100%[=============================================>]  42.23M  6.17MB/s   in 7.7s

2015-06-10 11:55:46 (5.46 MB/s) - 'git-annex-standalone-i386.tar.gz' saved [44282115/44282115]

tar: git-annex.linux/shimmed/git-fast-import/git-fast-import: Cannot write: No space left on device
tar: git-annex.linux/shimmed/gpg: Cannot mkdir: No space left on device
...
```

(is a bleeding-edge git-annex necessary? I have the jessie .deb installed anyway...)

If I hack around this with a bind-mount for the annex dir, I eventually get to a prompt to auth to github HTTPS. I don't think that's supposed to happen.

**Comment by db48x** [comment]
Yes, the bleeding-edge git-annex is necessary. We should probably handle this failure case more gracefully though.

**Comment by jmtd** [comment]
Thanks. I'll see about growing the partition a bit to move things onward, and (if possible) instruct IA.BAK to not take more than 95% or whatever of the volume... my next hurdle is that git annex wants to push to this repo @github via HTTPS when it does a sync. I'll keep poking...

**Comment by db48x** [comment]
This is not quite fixed, in the sense that we still fail even if it's slightly more graceful. A better fix would be to avoid deleting git-annex before we try to upgrade it.
