### ISSUE TITLE
Issue with configuration disk space

### ISSUE THREAD

**Issue by HarryC145** [ArchiveTeam/IA.BAK#41]
`Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       456G  6.2G  427G   2% /
How much of this disk space do you want to keep free, and not use for IA backup?
(You can free up space at any time by simply deleting files from the archives.)
To use entire disk, just hit Enter, or type in something like 100M, 200G, or 1T.
You must input a value of at least 100 megabytes.
keep free: 100M
./iabak-helper: line 204: bytesFromSize: command not found
./iabak-helper: line 204: [: -lt: unary operator expected
./iabak-helper: line 169: 1]: ambiguous redirect
./iabak-helper: line 172: bytesFromSize: command not found
./iabak-helper: line 172: bytesFromSize: command not found
*** not enough diskspace to reserve ***
keep free: 100m
./iabak-helper: line 204: bytesFromSize: command not found
./iabak-helper: line 204: [: -lt: unary operator expected
./iabak-helper: line 169: 1]: ambiguous redirect
./iabak-helper: line 172: bytesFromSize: command not found
./iabak-helper: line 172: bytesFromSize: command not found
*** not enough diskspace to reserve ***
keep free:
*** sorry, you may not leave this blank ***
keep free: 100M
./iabak-helper: line 204: bytesFromSize: command not found
./iabak-helper: line 204: [: -lt: unary operator expected
./iabak-helper: line 169: 1]: ambiguous redirect
./iabak-helper: line 172: bytesFromSize: command not found
./iabak-helper: line 172: bytesFromSize: command not found
*** not enough diskspace to reserve ***
keep free: 250M
./iabak-helper: line 204: bytesFromSize: command not found
./iabak-helper: line 204: [: -lt: unary operator expected
./iabak-helper: line 169: 1]: ambiguous redirect
./iabak-helper: line 172: bytesFromSize: command not found
./iabak-helper: line 172: bytesFromSize: command not found
*** not enough diskspace to reserve ***
keep free: 7gb
./iabak-helper: line 204: bytesFromSize: command not found
./iabak-helper: line 204: [: -lt: unary operator expected
./iabak-helper: line 169: 1]: ambiguous redirect
./iabak-helper: line 172: bytesFromSize: command not found
./iabak-helper: line 172: bytesFromSize: command not found
*** not enough diskspace to reserve ***
keep free: 5G
./iabak-helper: line 204: bytesFromSize: command not found
./iabak-helper: line 204: [: -lt: unary operator expected
./iabak-helper: line 169: 1]: ambiguous redirect
./iabak-helper: line 172: bytesFromSize: command not found
./iabak-helper: line 172: bytesFromSize: command not found
*** not enough diskspace to reserve ***
keep free: 100M`

Didnt seem to take any sort of space requirement, on Linux Mint Rosa. Rebooted iabak and it seems to carry on and shuf is now doing its thing before the download happens.

**Comment by kyrias** [comment]
The issue is that the `bytesFromSize` function is defined after it's used, so I'm not sure if 68cacc3d7eab687e234f43d3876e6898ac31005c was ever actually tested without `numfmt`.
