### ISSUE TITLE
connection stats aren't getting updated

### ISSUE THREAD

**Issue by db48x** [ArchiveTeam/IA.BAK#49]
The stats pages are getting updated (mostly), and the other stats we're storing in graphite seem to be getting updated, but the connectionstats aren't. Carbon is running and receiving connections, graphite-web is fine, etc.

**Comment by km09** [comment]
Seems to be an issue with older shards. Shards 17-19 are updating

**Comment by db48x** [comment]
Ok, that's confusing.

**Comment by km09** [comment]
Graphs are updating again after a server reboot.
