### ISSUE TITLE
Problem with setup on Debian Wheezy

### ISSUE THREAD

**Issue by Lazuruz** [ArchiveTeam/IA.BAK#54]
During setup this error appears.  Have tested on two machines running the same OS and the problem exists in both places.  

`/usr/bin/flock: cannot open lock file .git/annex/iasyncer.lock: No such file or directory`

Edit: I have also tried the manual install of annex and it did not help.

Edit2:  ~~The permissions and ownership from the git repo appear to be incorrect.~~

**Comment by db48x** [comment]
Ah, what permissions and ownership does the git repo end up with?

**Comment by Lazuruz** [comment]
much of the repo ends up in root:root .... even though I pulled using a user account.  IS this right?

**Comment by db48x** [comment]
No, that's quite unexpected.

**Comment by Lazuruz** [comment]
Ok scratch the permissions issue, that was on me.  Apparently my git was doing some funky stuff.  Reinstalled and cloned repo again without any issues.
