### ISSUE TITLE
script should check the free space reservation for common errors

### ISSUE THREAD

**Issue by db48x** [ArchiveTeam/IA.BAK#7]
I accidentally typed in 1T instead of 1G, but I don't have anywhere near 1 terabyte of disk space available at the moment. git annex correctly avoided downloading anything at all, but the script could have checked that my input made some sense first.

It could also check that the input makes sense as a size as well.

**Comment by cancerAlot** [comment]
Do you mean something like that?
https://github.com/ArchiveTeam/IA.BAK/commit/671518992d6b08dfe9fb9f4f5f857ce8947b59fc
